Update upload-script

diff --git a/upload-script b/upload-script
--- a/upload-script
+++ b/upload-script
@@ -25,19 +25,15 @@ fi
 # Ensure that there is a pattern specified.
 #
 if [[ -z "$INPUT_ARGS" ]]; then
-    echo "Missing file (pattern) to upload."
-    exit 1
+  echo "Missing file (pattern) to upload."
+  exit 1
 fi
-
 
 #
 # Sanity-check, show our arguments.
 #
 echo "Arguments : ${INPUT_ARGS}"
 echo "Release ID: ${INPUT_RELEASEID}"
-
-
-
 
 #
 # In the past we invoked a build-script to generate the artifacts
@@ -51,9 +47,9 @@ echo "Release ID: ${INPUT_RELEASEID}"
 # Have we found any artifacts?
 found=
 for file in $INPUT_ARGS; do
-    if [ -e "$file" ]; then
-        found=1
-    fi
+  if [ -e "$file" ]; then
+    found=1
+  fi
 done
 
 #
@@ -61,127 +57,125 @@ done
 #
 if [ -z "${found}" ]; then
 
-    echo "*****************************************************************"
-    echo " "
-    echo " Artifacts are missing, and this action no longer invokes the "
-    echo " legacy-build script."
-    echo " "
-    echo " Please see the README.md file for github-action-publish-binaries"
-    echo " which demonstrates how to build AND upload artifacts."
-    echo " "
-    echo "*****************************************************************"
+  echo "*****************************************************************"
+  echo " "
+  echo " Artifacts are missing, and this action no longer invokes the "
+  echo " legacy-build script."
+  echo " "
+  echo " Please see the README.md file for github-action-publish-binaries"
+  echo " which demonstrates how to build AND upload artifacts."
+  echo " "
+  echo "*****************************************************************"
 
-    exit 1
+  exit 1
 fi
-
 
 #
 # Prepare the headers for our curl-command.
 #
 AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
 
-
 #
 # Get the release ID
 #
 if [ -z "${INPUT_RELEASEID}" ]; then
 
-    #
-    # Not specified?  Use the one from the payload
-    #
-    RELEASE_ID=$(jq --raw-output '.release.id' "$GITHUB_EVENT_PATH")
+  #
+  # Not specified?  Use the one from the payload
+  #
+  RELEASE_ID=$(jq --raw-output '.release.id' "$GITHUB_EVENT_PATH")
 
-    echo "Discovered RELEASE_ID: ${RELEASE_ID}"
+  echo "Discovered RELEASE_ID: ${RELEASE_ID}"
 else
 
-    #
-    # Otherwise use the supplied value.
-    #
-    RELEASE_ID="${INPUT_RELEASEID}"
+  #
+  # Otherwise use the supplied value.
+  #
+  RELEASE_ID="${INPUT_RELEASEID}"
 
-    echo "Using supplied RELEASE_ID: ${RELEASE_ID}"
+  echo "Using supplied RELEASE_ID: ${RELEASE_ID}"
 fi
-
 
 #
 # For each matching file..
 #
 for file in $INPUT_ARGS; do
 
-    echo "Processing file ${file}"
+  echo "Processing file ${file}"
 
-    if [ ! -e "$file" ]; then
-        echo "***************************"
-        echo " file not found - skipping."
-        echo "***************************"
-        continue
-    fi
+  if [ ! -e "$file" ]; then
+    echo "***************************"
+    echo " file not found - skipping."
+    echo "***************************"
+    continue
+  fi
 
-    if [ ! -s "$file" ]; then
-        echo "**************************"
-        echo " file is empty - skipping."
-        echo "**************************"
-        continue
-    fi
+  if [ ! -s "$file" ]; then
+    echo "**************************"
+    echo " file is empty - skipping."
+    echo "**************************"
+    continue
+  fi
 
+  FILENAME=$(basename "${file}")
 
-    FILENAME=$(basename "${file}")
+  UPLOAD_URL="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${FILENAME}"
+  echo "Upload URL is ${UPLOAD_URL}"
 
-    UPLOAD_URL="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${FILENAME}"
-    echo "Upload URL is ${UPLOAD_URL}"
+  # Generate a temporary file.
+  tmp=$(mktemp)
 
-    # Generate a temporary file.
-    tmp=$(mktemp)
+  # Upload the artifact - capturing HTTP response-code in our output file.
+  response=$(
+    curl \
+    -sSL \
+    -XPOST \
+    -H "${AUTH_HEADER}" \
+    --upload-file "${file}" \
+    --header "Content-Type:application/octet-stream" \
+    --write-out "%{http_code}" \
+    --output $tmp \
+    "${UPLOAD_URL}"
+  )
 
-    # Upload the artifact - capturing HTTP response-code in our output file.
-    response=$(curl \
-        -sSL \
-        -XPOST \
-        -H "${AUTH_HEADER}" \
-        --upload-file "${file}" \
-        --header "Content-Type:application/octet-stream" \
-        --write-out "%{http_code}" \
-        --output $tmp \
-        "${UPLOAD_URL}")
-
-    # If the curl-command returned a non-zero response we must abort
-    if [ "$?" -ne 0 ]; then
-        echo "**********************************"
-        echo " curl command did not return zero."
-        echo " Aborting"
-        echo "**********************************"
-        cat $tmp
-        rm $tmp
-        exit 1
-    fi
-
-    # If upload is not successful, we must abort
-    if [ $response -ge 400 ]; then
-        echo "***************************"
-        echo " upload was not successful."
-        echo " Aborting"
-        echo " HTTP status is $response"
-        echo "**********************************"
-        cat $tmp
-        rm $tmp
-        exit 1
-    fi
-
-    # Show pretty output, since we already have jq
-    cat $tmp | jq .
+  # If the curl-command returned a non-zero response we must abort
+  if [ "$?" -ne 0 ]; then
+    echo "**********************************"
+    echo " curl command did not return zero."
+    echo " Aborting"
+    echo "**********************************"
+    cat $tmp
     rm $tmp
+    exit 1
+  fi
 
-    TEMP_FILENAME=${FILENAME}
-    replaceBrackets="."
-    tempFileName="${TEMP_FILENAME/(/"$replaceBrackets"}"
-    fileName="${tempFileName/)/"$replaceBrackets"}"
-    downloadUrl="https://github.com/${GITHUB_REPOSITORY}/releases/download/"
+  # If upload is not successful, we must abort
+  if [ $response -ge 400 ]; then
+    echo "***************************"
+    echo " upload was not successful."
+    echo " Aborting"
+    echo " HTTP status is $response"
+    echo "**********************************"
+    cat $tmp
+    rm $tmp
+    exit 1
+  fi
 
-    echo "downloadUrl:  ${downloadUrl}"
-    echo "fileName:  ${fileName}"
-    echo "FILENAME:  ${FILENAME}"
-    echo ::set-output name=url::"$downloadUrl"
-    echo ::set-output name=file_name::"${fileName}"
-    echo ::set-output name=firebase_file_name::"${FILENAME}"
+  # Show pretty output, since we already have jq
+  cat $tmp | jq .
+  rm $tmp
+
+  TEMP_FILENAME=${FILENAME}
+  replaceBrackets="."
+  tempFileName="${TEMP_FILENAME/(/"$replaceBrackets"}"
+  fileName="${tempFileName/)/"$replaceBrackets"}"
+  downloadUrl="https://github.com/${GITHUB_REPOSITORY}/releases/download/"
+
+  echo "downloadUrl:  ${downloadUrl}"
+  echo "fileName:  ${fileName}"
+  echo "FILENAME:  ${FILENAME}"
+  echo url="${downloadUrl}" >> $GITHUB_OUTPUT
+  echo file_name="${fileName}" >> $GITHUB_OUTPUT
+  echo firebase_file_name="${FILENAME}" >> $GITHUB_OUTPUT
 
 done
